travis:
  secure:
    BINSTAR_TOKEN: VHMAnleCjgQzQUUHnTcSawX9Po6NwYP/J89dOlrFcUqFyjzPuEaSso0O6WYjqjnIcUh3jDWwXV+Whdzx96z2EzyeTHuRdGJ3gKaIRAmtAKBSNaSqxe97JqCPIZOBWPp9YZUoEZxbGJLu7bhprmknODb658E25mx6vKTtU2qzdXXhYON8RSErkRqcyjEJvWXeEHggTjtB1wdpJYkiF46tuaC2sxyBJVjm3SkrfOo6000tkh1MOi1zGCXwtlPeHgShmQvlGcKMgsdicxz0V5yQmEeNI8fSFXifiyaMSp1mzFJNG9I8O//Kbwej/Uf51UhVssn1VZPKbsa46Yv0+tmfSUxEjwzIaipoPQfOaC56+67HkyWVVYqznykNZYlbq37BGbsmo5/Mqm/QyR36b3d4sj+QuQMWgf4NwS1sFP+uMpoAZf+1NgOacEH7tqt9Alwq+07Ii8VuiE5NrXqjX9foir1GqcOH/tRAca9F8gZ73s0hb4vgZjnciyK94fodXFsm3FHdyUdGrKT+lKfZxLuQFEGF0dZKlylajO/QrGgRvRUb48+xhB60wR9rzRDdym0KF6IMimc8eXSZ+pkeSPEe5ayOCwIDPZM0MYueoEmqXZorybgczH6Ed8fk+y+HtYcWK7gWCwO7/WD6JYvPiV1CZhKRFwAhBUxuIBLeW44loOI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
